### ISSUE TITLE
Making HIPAA compliant dApps

### ISSUE THREAD

**Issue by rbharath** [computablelabs/computable.js#21]
We anticipate that `datamined` will be used to store sensitive data. In the U.S, sensitive medical/healthcare data requires [HIPAA](http://www.onlinetech.com/resources/references/what-is-hipaa-compliance) compliance. While literature has emerged on HIPAA compliant architectures, it's not clear what a HIPAA compliant dApp would look like. Let's use this issue to track the changes/features that will be needed to bring `datamined` into HIPAA compliance.

Feel free to chime in if you have comments/thoughts on what HIPAA compliance means for dApps in general.

**Comment by rbharath** [comment]
Some good feedback via Twitter. Highlights:

- A private blockchain stored on a hospital server (for example) would be easiest path towards HIPAA compliance, but since `datamined` is a public protocol, not a feasible path.
- Relationships between patients/users and doctors is covered by HIPAA. Generalizing, data usage/transaction records should probably be private for security. This might require some type of anonymization of transactions, a la Zcash or Monero. Will need to do some significant technical scoping to plan this out.

**Comment by rbharath** [comment]
The Medrec project talks about design of HIPAA compliant blockchain (private I believe): https://www.healthit.gov/sites/default/files/5-56-onc_blockchainchallenge_mitwhitepaper.pdf

**Comment by acoravos** [comment]
The team at Aptible has some great resources for HIPAA compliance for developers: 
https://www.aptible.com/resources/

**Comment by rbharath** [comment]
@acoravos Thanks for the pointer! I particularly liked the section on technical safeguards:

- Authentication
- Access control and session management
- Audit logging
- Encryption of data at rest
- Encryption of data in transit, and
- Data integrity checks (as needed)

These seem like solid requirements `datamined` should implement.

**Comment by rbharath** [comment]
This is an important thread, but going to close since we're very far from HIPAA compliance for now :)
