### ISSUE TITLE
Problems running tests (nothing in computable directory)

### ISSUE THREAD

**Issue by RobertStewart** [computablelabs/computable.js#58]
After resolving issue #56 with a switch to node 8.11.1, I unsurprisingly had to do an `npm rebuild` to get past
```
Error: The module '/Users/rstewart/src/computable.js/node_modules/scrypt/build/Release/scrypt.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```
When I then ran `npm run test`, I got
```
% npm run test

> @computablelabs/computable.js@0.1.0 test /Users/rstewart/src/computable.js
> jasmine-ts ./spec/**/*.spec.ts

Error: Cannot find module '../../../computable/build/contracts/Parameterizer.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rstewart/src/computable.js/spec/computable/parameterizer/parameterizer.spec.ts:23:46)
```
The top level computable dir is empty and the spec/computable dir doesn't have a build dir. Is there anything else I need to do to get a clean build other than `npm rebuild`?

**Comment by robrobbins** [comment]
the contents of the submodule should hydrate with the `git submodule update --remote` command

**Comment by RobertStewart** [comment]
That solved it! When I was trying to debug the other problem, I did a fresh git clone to make sure I could reproduce the problem. I had previously run git submodule init, but forgot to do it again on the fresh clone. All tests now pass.
