### ISSUE TITLE
Encrypting data storage locations

### ISSUE THREAD

**Issue by rgrchen** [computablelabs/computable.js#6]
Ledger contains pointers to where data is stored but the pointers themselves will require encryption so that only permissioned users receive access. One way I've thought about this is a multi-sig approach where data owners grant permissions by signing a data transaction with their private key for users that can uniquely countersign with their private key. Data is then pushed to permissioned user for computation. "Pushing" here also requires more thought. For example, data could be copied to a temporary storage location that the multi-sig transaction reveals for users to then grab (one-time before deletion), without revealing where original copies of data are located (and encrypted).

https://github.com/datamined/datamined/blob/0c805273deedd45ace097aea3148da1b05844706/examples/workflow.py#L19-L24

**Comment by rbharath** [comment]
@rgrchen Good comments here! I like the multi-sig ideas here. Will try to see if I can hunt down or put together some example code.

One add-on thought is that our current design allows compute nodes full visibility into the data stored at the ledger, assuming that data owner has granted access. We should also start spec-ing out "secure" accesses, where data owner only allows compute nodes access to perturbed data. This could be simple noise addition to start, but perhaps some type of homomorphic encryption in more sophisticated use case.
