### ISSUE TITLE
Tests fail due to computable submodule being out of sync

### ISSUE THREAD

**Issue by c0gent** [computablelabs/computable.js#87]
After following the directions in the README, `npm run test` fails because it can't find `EIP20.json`. This is due to the the recent move from the EIP20 to ERC20 token in the `computable` repo.

https://github.com/computablelabs/computable.js/pull/86 fixes this temporary problem but looking forward, might it be better to keep the `computable` submodule pinned to a separate, special branch within the `computable` repo which specifically exists to keep in sync with `computable.js` master and remove the `git submodule update --remote` line from the README instructions? This might avert this problem in the future. Let me know if I've misunderstood anything.

**Comment by robrobbins** [comment]
this is known. we are in the middle of a big contract change that didn't get reviewed on friday so the 2 are out of sync -- you got directed to check out the repos in the middle of it....

**Comment by c0gent** [comment]
Yup, I assumed as much.

**Comment by robrobbins** [comment]
@c0gent #89 fixes. should be in tomorrow

It's not a bad idea to "lock" the submodule, but, it's super early days and volatile changes are the norm atm. 

I'm going to have a couple of short blog posts soon about why I made the decisions I did regarding these 2 repos. It seems a bit odd, submoduling it this way, but it's going to prove to be the right move for us.

* we won't maintain 2 JS environments:
    * solidity is strange at this point. you don't test your code in the language you write it in. you attempt to mock the environment with js. this smacks of mistakes made with rails/capybara where you end up testing your environment and not your code. i think better testing environments are around the corner for .sol (I also believe, longer term, we'll be writing the contracts in rust and testing them there [wasm])

**Comment by c0gent** [comment]
Makes sense. I think the way you've organized the repos is a perfectly good setup. You'll eventually need to do something to lock the versions though imho.

I've seen some of the early Rust contract stuff and I've been following playing around with Wasm for over a year now. Looks very promising. Rust will definitely be one of the top languages for Wasm. It could be a great language for contracts but we'll see what happens. 

Solidity *is* strange. When I use it (and I'm only just now picking it up) alarm bells go off in my head for how potentially dangerous so many things could be. If it is to survive (I'm sort of betting against it) it will need massive amounts of verification/testing via tooling. I'm not sure but it just doesn't seem like a very good language for something as mission critical as contracts. A more innovative and specialized approach to language design is needed. Something that allows/encourages more kinds of static verification of things sort of like how Rust allows the compiler to 100% verify safety. I don't know. Contracts are a whole different beast.

I'll go ahead and close. Thanks for your comments! I'll keep an eye on the blog.
